### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by ghost** [dmyers/laravel-pages#2]
![Capture3](https://github.com/dmyers/laravel-pages/assets/168183411/0f3a95ef-b786-41fd-9329-7c94f0ef1fbd)
when i click on time sheet link in my home page  the error shows 404 page not found 
although the page is formed and the code is written 
  <li class="nav-item">
                        <a class="nav-link" href="{{ url('timesheets/day-view') }}">timesheets</a>
                    </li>
in day-view,blade,php
@extends('static')
@section('content')
@endsection

**Comment by sohaib10000** [comment]
![Uploading Capture3.PNG…]()

**Comment by dmyers** [comment]
Sorry this is not really maintained. Laravel now has basically the same idea now 11 years later as a package you can drop in I would recommend using instead: https://laravel.com/docs/11.x/folio
